# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=11)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(max_length=30)),
                ('other_name', models.CharField(max_length=30)),
                ('relationship', models.CharField(choices=[('Bro', 'Brother'), ('Sis', 'Sister'), ('Cousin', 'Cousin'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt')], max_length=30)),
                ('contact_Address', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
                ('receipt_num', models.CharField(max_length=4, unique=True)),
                ('deposit', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('other_name', models.CharField(max_length=30)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs')], max_length=30)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], max_length=30)),
                ('home_town', models.CharField(max_length=100)),
                ('local_gov', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('nationality', models.CharField(default='Nigeria', max_length=30)),
                ('contact_phone', models.CharField(max_length=11)),
                ('home_address', models.CharField(max_length=100)),
                ('passport', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=30)),
                ('reg_num', models.CharField(max_length=30)),
                ('programme_fee', models.IntegerField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SPCI.PersonalDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=30)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPCI.Programme')),
            ],
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPCI.Programme'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPCI.PersonalDetails'),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='referrer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SPCI.PersonalDetails'),
        ),
        migrations.AddField(
            model_name='courses',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPCI.Semester'),
        ),
    ]
