# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPCI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='payment_complete',
            field=models.BooleanField(default=False),
        ),
    ]
