# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPCI', '0002_paymentdetail_payment_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='student',
        ),
    ]
