# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPCI', '0003_remove_paymentdetail_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='id',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='id',
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='referrer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SPCI.PersonalDetails'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='receipt_num',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='program',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
