# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPCI', '0004_auto_20161208_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='program_code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPCI.PersonalDetails'),
        ),
    ]
