# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPCI', '0005_auto_20161228_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_num', models.CharField(max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SPCI.PersonalDetails')),
            ],
        ),
        migrations.AlterField(
            model_name='programme',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SPCI.Registered'),
        ),
    ]
