# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPCI', '0006_auto_20161228_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='reg_num',
        ),
    ]
